### ISSUE TITLE
Missing Headers (AnalogSignal and FrequencyPlot)

### ISSUE THREAD

**Issue by Yannick-ll** [borisRadonic/AudioAnalyzer#1]
Hi, Thank you for sharing !
I had a problem while compiling. I was missing two headers : 

../scopeplotcurve.cpp:3:10: fatal error: AnalogSignal.h: Aucun fichier ou dossier de ce type
 #include "AnalogSignal.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../formanalyzer.cpp:1:0:
../formanalyzer.h:7:10: fatal error: FrequencyPlot.h: Aucun fichier ou dossier de ce type
 #include "FrequencyPlot.h"
          ^~~~~~~~~~~~~~~~~

Could you please help me ?

**Comment by borisRadonic** [comment]
Hi,
Which compiler do you use? Have you installed QT Designer.Have you installed "Qwt-6.1.2"  If you install "Qwt-6.1.2" in other folder than "C:\Qwt-6.1.2\src", please modify INCLUDEPATH in the QT project file "audioanalyzer.pro"

AnalogSignal.h is in GIT and I do not see any problem why you would not be able to compile it. You have to configure your IDE (QT Designer)and Compiler...
Best RagardsBoris










    Am Mittwoch, 11. Oktober 2023 um 10:51:12 MESZ hat Yannick-ll ***@***.***> Folgendes geschrieben:  
 
 


Hi, Thank you for sharing !
I had a problem while compiling. I was missing two headers :

../scopeplotcurve.cpp:3:10: fatal error: AnalogSignal.h: Aucun fichier ou dossier de ce type
#include "AnalogSignal.h"
^~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../formanalyzer.cpp:1:0:
../formanalyzer.h:7:10: fatal error: FrequencyPlot.h: Aucun fichier ou dossier de ce type
#include "FrequencyPlot.h"
^~~~~~~~~~~~~~~~~

Could you please help me ?

**Comment by Yannick-ll** [comment]
Hi,
Thank you for your quick response.

This is my config : 
- Ubuntu 20.04
- Qt 5.12.8  (GCC 9.3.0, 64 bit)
- Qt Creator 4.11.0
- Qwt installed under : /usr/local/qwt-6.1.2/

I was a bit "lazy", sorry. The headers are there. Just few difference with upper/lowercase in the naming :-). For instance, "AnalogSignal.h" instead of "analogsignal.h". 
I updated the names wherever it was necesary.

I also did the following change : 
- replace "#define __WINDOWS_ASIO__"  with  "#define __LINUX_ALSA__" in RtAudio.h

But I still have some errors like : 

In file included from ../RtAudio/include/asiodrivers.cpp:2:
../RtAudio/include/asiodrivers.h:7:10: fatal error: CodeFragments.hpp: Aucun fichier ou dossier de ce type
    7 | #include "CodeFragments.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
../RtAudio/include/asio.cpp:254: warning: ignoring ‘#pragma export off’ [-Wunknown-pragmas]
  254 | #pragma export off
      | 
make: *** [Makefile:915 : asiodrivers.o] Erreur 1
make: *** Attente des tâches non terminées....
cc1plus: error: ‘::main’ must return ‘int’
../RtAudio/include/asio.cpp:45:11: error: conflicting declaration of ‘ASIOError ASIOInit(ASIODriverInfo*)’ with ‘C’ linkage
   45 | ASIOError ASIOInit(ASIODriverInfo *info)
      |           ^~~~~~~~


I am certainly missing something, but I don't know what ...

**Comment by borisRadonic** [comment]
Hi,I have tested it a more than five years ago on Windows and Mac. It is possible to compile it for Linux, but i have no running Linux PC and no time… Sorry,I wisch you a good luck. Best RegardsBoris


Gesendet von Yahoo Mail für iPhone


Am Mittwoch, Oktober 11, 2023, 1:35 PM schrieb Yannick-ll ***@***.***>:




Hi,
Thank you for your quick response.

This is my config :
   
   - Ubuntu 20.04
   - Qt 5.12.8 (GCC 9.3.0, 64 bit)
   - Qt Creator 4.11.0
   - Qwt installed under : /usr/local/qwt-6.1.2/

I was a bit "lazy", sorry. The headers are there. Just few difference with upper/lowercase in the naming :-). For instance, "AnalogSignal.h" instead of "analogsignal.h".
I updated the names wherever it was necesary.

I also did the following change :
   
   - replace "#define WINDOWS_ASIO" with "#define LINUX_ALSA" in RtAudio.h

But I still have some errors like :

In file included from ../RtAudio/include/asiodrivers.cpp:2:
../RtAudio/include/asiodrivers.h:7:10: fatal error: CodeFragments.hpp: Aucun fichier ou dossier de ce type
7 | #include "CodeFragments.hpp"
| ^~~~~~~~~~~~~~~~~~~
compilation terminated.
../RtAudio/include/asio.cpp:254: warning: ignoring ‘#pragma export off’ [-Wunknown-pragmas]
254 | #pragma export off
|
make: *** [Makefile:915 : asiodrivers.o] Erreur 1
make: *** Attente des tâches non terminées....
cc1plus: error: ‘::main’ must return ‘int’
../RtAudio/include/asio.cpp:45:11: error: conflicting declaration of ‘ASIOError ASIOInit(ASIODriverInfo*)’ with ‘C’ linkage
45 | ASIOError ASIOInit(ASIODriverInfo *info)
| ^~~~~~~~

I am certainly missing something, but I don't know what ...

**Comment by borisRadonic** [comment]
all headers are here

**Comment by borisRadonic** [comment]
Ok
